packages:
  # agent tars
  - 'agent-tars/*'
  # mcp (tarko)
  - 'mcp-agent'
  - 'mcp-agent-interface'
  # low-level (tarko)
  - 'tarko/*'
  # ci/cd
  - 'pnpm-toolkit'
  # benchmark
  - 'benchmark/*'
  # docs
  - 'websites/main'
  - 'websites/docs'
  # gui agent
  - 'gui-agent/*'
