packages:
  # agent tars
  - 'agent-tars/*'
  # gui agent
  - 'gui-agent/*'
  # low-level (tarko)
  - 'tarko/*'
  # benchmark
  - 'benchmark/*'
  # docs
  - 'websites/*'
  # seed mcp agent
  - 'seed-mcp-agent'
