on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'main'

name: CI Test, Typecheck, E2E
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test
  cancel-in-progress: true
env:
  CI: true
  NODE_OPTIONS: --max-old-space-size=8192
  HUSKY: 0

jobs:
  test:
    name: Test & Typecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm@9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run typecheck
        run: pnpm run typecheck
      - name: Run test
        run: pnpm run test

  e2e:
    name: E2E
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm@9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Python setuptools
        if: matrix.os == 'macos-latest'
        run: brew install python-setuptools
      - name: Install appdmg
        if: matrix.os == 'macos-latest'
        run: npm install -g appdmg
      - name: Install dependencies
        run: pnpm install
      - name: Run build dist
        run: pnpm run build:deps && pnpm run build:dist
      - name: Run e2e
        run: pnpm run test:e2e
      - name: Run test make
        run: pnpm run make --enable-logging
